import type { Metadata } from 'next'
import '@/styles/globals.css'

import { Geist, Geist_Mono } from 'next/font/google'
import { BiSupport } from 'react-icons/bi'

import { Footer } from '@/components/layout/Footer'
import { Navbar } from '@/components/layout/Navbar'
import { ThemeInitializer } from '@/features/theme/components/ThemeInitializer'
import { QueryProvider } from '@/providers/QueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='flex min-h-full flex-col'>
        <QueryProvider>
          <button className='fixed right-0 bottom-0 z-50 m-5 rounded-full bg-white p-2 text-black opacity-95 shadow-md transition duration-200 hover:opacity-85 hover:shadow-lg active:opacity-75 dark:border dark:border-white/20 dark:bg-black dark:text-white'>
            <BiSupport className='h-6 w-6' />
          </button>
          <Navbar />
          <ThemeInitializer />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  )
}
